services:
  # Go Backend API
  go-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
      - PORT=8080

  # Vue Frontend
  vue-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173" 
    volumes:
      - ./frontend:/app # Mount local frontend for hot reload
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://go-backend:8080
    depends_on:
      - go-backend
    command: npm run dev -- --host 0.0.0.0 --port 5173 
