version: '3.8'

services:
  # Go Backend API
  go-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  # Vue Frontend
  vue-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - go-backend
